development:
  adapter: postgresql
  encoding: unicode
  database: perfectsell_development
  pool: 5
  host: localhost
  username: postgres
  password: NinaZilli8888

test:
  adapter: postgresql
  encoding: unicode
  database: perfectsell_test
  pool: 5
  username: postgres
  password: NinaZilli8888

#staging:
  #url: <%= ENV['DATABASE_URL'] %>

#production:
  #url: <%= ENV['DATABASE_URL'] %>