development:
  adapter: postgresql
  encoding: unicode
  database: Perfect_Sell_DB #hhvhkmnb
  pool: 5
  host: localhost #arjuna.db.elephantsql.com
  username: postgres #hhvhkmnb
  password: NinaZilli8888 #srfCiRDPkvk1T9SwPJG5KYQ3U7fTmBwg

test:
  adapter: postgresql
  encoding: unicode
  database: Perfect_Sell_DB_Test
  pool: 5
  username: postgres
  password: NinaZilli8888

#staging:
  #url: <%= ENV['DATABASE_URL'] %>

#production:
  #url: <%= ENV['DATABASE_URL'] %>